import type { IDescriptionProp } from '@/base-ui/descriptions';
export const devDependencies: IDescriptionProp[] = [
  { name: '@commitlint/cli', description: '^17.6.7' },
  { name: '@commitlint/config-conventional', description: '^17.6.7' },
  { name: '@iconify-json/ep', description: '^1.1.12' },
  { name: '@iconify-json/wi', description: '^1.1.5' },
  { name: '@typescript-eslint/eslint-plugin', description: '^5.4.0' },
  { name: '@typescript-eslint/parser', description: '^5.4.0' },
  { name: '@vue/cli-plugin-babel', description: '~5.0.0' },
  { name: '@vue/cli-plugin-eslint', description: '~5.0.0' },
  { name: '@vue/cli-plugin-typescript', description: '~5.0.0' },
  { name: '@vue/cli-service', description: '~5.0.0' },
  { name: '@vue/eslint-config-typescript', description: '^9.1.0' },
  { name: 'commitizen', description: '^4.3.0' },
  { name: 'cz-conventional-changelog', description: '3.3.0' },
  { name: 'eslint', description: '^7.32.0' },
  { name: 'eslint-config-prettier', description: '^8.3.0' },
  { name: 'eslint-plugin-prettier', description: '^4.0.0' },
  { name: 'eslint-plugin-vue', description: '^8.0.3' },
  { name: 'husky', description: '^8.0.0' },
  { name: 'less', description: '^4.0.0' },
  { name: 'less-loader', description: '^8.0.0' },
  { name: 'prettier', description: '^2.4.1' },
  { name: 'typescript', description: '~4.5.5' },
  { name: 'unplugin-auto-import', description: '^0.16.6' },
  { name: 'unplugin-icons', description: '^0.16.5' },
  { name: 'unplugin-vue-components', description: '^0.25.1' }
];
